https://dados.gov.br/dataset/serie-historica-de-precos-de-combustiveis-por-revenda

https://www.gov.br/anp/pt-br/assuntos/precos-e-defesa-da-concorrencia/precos/precos-revenda-e-de-distribuicao-combustiveis/levantamento-de-precos-de-combustiveis

In [2]:
import pandas as pd

In [3]:
!ls entrada/

ca-2015-01.csv.bz2  ca-2017-01.csv.bz2	ca-2019-01.csv.bz2  ca-2021-01.csv.bz2
ca-2015-02.csv.bz2  ca-2017-02.csv.bz2	ca-2019-02.csv.bz2  ca-2021-02.csv.bz2
ca-2016-01.csv.bz2  ca-2018-01.csv.bz2	ca-2020-01.csv.bz2  ca-2022-01.csv.bz2
ca-2016-02.csv.bz2  ca-2018-02.csv.bz2	ca-2020-02.csv.bz2

In [4]:
!bzcat entrada/ca-2022-01.csv.bz2 | head -5

bzcat: I/O or other error, bailing out.  Possible reason follows.
bzcat: Broken pipe
	Input file = entrada/ca-2022-01.csv.bz2, output file = (stdout)

In [5]:
df = pd.read_csv("entrada/ca-2021-02.csv.bz2", sep=";", decimal=",", nrows=10000, encoding="iso8859")
#df = pd.read_csv("entrada/ca-2017-02.csv.bz2", sep=";", decimal=",", nrows=10000)
#df = pd.read_csv("entrada/ca-2022-01.csv.bz2", sep=";", nrows=10000, decimal=",")
df.head(5)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,CE,MARACANAU,BEZERRA & MENDES COMERCIAL DE PETRÓLEO LTDA.,05.397.086/0001-51,RODOVIA MARANGUAPE - FORTALEZA - KM 06,S/N,NaN,PARQUE LUZARDO VIANA,61910-000,GASOLINA ADITIVADA,01/07/2021,5.699,NaN,R$ / litro,IPIRANGA
1,NE,CE,MARACANAU,BEZERRA & MENDES COMERCIAL DE PETRÓLEO LTDA.,05.397.086/0001-51,RODOVIA MARANGUAPE - FORTALEZA - KM 06,S/N,NaN,PARQUE LUZARDO VIANA,61910-000,GASOLINA,01/07/2021,5.499,NaN,R$ / litro,IPIRANGA
2,NE,CE,MARACANAU,BEZERRA & MENDES COMERCIAL DE PETRÓLEO LTDA.,05.397.086/0001-51,RODOVIA MARANGUAPE - FORTALEZA - KM 06,S/N,NaN,PARQUE LUZARDO VIANA,61910-000,DIESEL S10,01/07/2021,4.699,NaN,R$ / litro,IPIRANGA
3,NE,CE,MARACANAU,BEZERRA & MENDES COMERCIAL DE PETRÓLEO LTDA.,05.397.086/0001-51,RODOVIA MARANGUAPE - FORTALEZA - KM 06,S/N,NaN,PARQUE LUZARDO VIANA,61910-000,ETANOL,01/07/2021,5.200,NaN,R$ / litro,IPIRANGA
4,NE,CE,MARACANAU,LUIZA GLAURIA R T MENEZES,03.602.329/0001-10,ESTRADA FORTALEZA MARANGUAPE,S/N,NaN,KAGADO,61901-410,GASOLINA,01/07/2021,5.490,NaN,R$ / litro,VIBRA ENERGIA

In [6]:
df.describe(include='all')

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
count,10000,10000,10000,10000,10000,10000,9996,2138,9966,10000,10000,10000,10000.000000,0.0,10000,10000
unique,5,26,242,2308,2500,1768,1499,403,1342,2005,6,4,NaN,NaN,2,37
top,SE,SP,FORTALEZA,SOBRAL & PALACIO PETROLEO LTDA,05.616.026/0001-82,AVENIDA GETULIO VARGAS,S/N,0,CENTRO,17400-000,GASOLINA,05/07/2021,NaN,NaN,R$ / litro,BRANCA
freq,5176,3335,417,48,10,99,761,189,1613,59,2502,5202,NaN,NaN,9753,3532
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.083503,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.717769,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.969000,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.490000,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.999000,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.699000,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.999000,NaN,NaN,NaN

In [7]:
for col in df.columns:
    print(df[[col]].value_counts(), "\n")

Regiao - Sigla
SE                5176
NE                2106
S                 1540
N                  644
CO                 534
dtype: int64

Estado - Sigla
SP                3335
RJ                 894
MG                 708
RS                 622
BA                 570
CE                 500
SC                 481
PR                 437
PE                 369
GO                 265
ES                 239
AM                 210
MT                 200
PB                 185
PA                 163
AL                 133
RN                 101
SE                  92
PI                  88
AC                  86
TO                  81
MS                  69
MA                  68
RO                  62
AP                  30
RR                  12
dtype: int64

Municipio
FORTALEZA               417
SALVADOR                365
CAMPINAS                183
MANAUS                  177
RIO DE JANEIRO          149
                       ...
TRINDADE                  4
GOVERNADOR VALADARES      4
CARIACICA                 3
ITATIBA                   3
CACHOEIRINHA              3
Length: 242, dtype: int64

Revenda
SOBRAL & PALACIO PETROLEO LTDA                                             48
SIM REDE DE POSTOS LTDA                                                    44
COMERCIAL BUFFON COMBUSTIVEIS E TRANSPORTES LIMITADA                       36
COMPANHIA BRASILEIRA DE DISTRIBUICAO                                       32
CARREFOUR COMERCIO E INDUSTRIA LTDA                                        29
                                                                           ..
AUTO POSTO SUL BRASIL LTDA EPP                                              1
POSTO COLONIAL NORTE LTDA                                                   1
AUTO POSTO TERCEIRO MILÊNIO LTDA                                            1
REDE OSORIO'S 410 DE NITEROI COMERCIO DE GAS NATURAL PARA VEICULOS LTDA     1
MARKA COMERCIO DE COMBUSTIVEIS LTDA                                         1
Length: 2308, dtype: int64

CNPJ da Revenda
 05.616.026/0001-82    10
 07.569.563/0001-44    10
 03.581.094/0001-28    10
 08.699.770/0001-86    10
 46.396.826/0001-12    10
                       ..
 04.707.467/0006-31     1
 08.949.137/0001-07     1
 12.241.406/0001-45     1
 09.107.026/0001-08     1
 05.983.192/0003-89     1
Length: 2500, dtype: int64

Nome da Rua
AVENIDA GETULIO VARGAS            99
AVENIDA BRASIL                    80
RODOVIA BR 101                    70
RODOVIA WASHINGTON LUIZ           41
AVENIDA DOS IMIGRANTES            39
                                  ..
RUA JOSÉ VIEIRA CAULA              1
RUA GUANABARA                      1
AV. BRASIL, S/N                    1
AVENIDA PADRE JULIO M LOMBAERD     1
AVENIDA BOA ESPERANCA              1
Length: 1768, dtype: int64

Numero Rua
S/N           761
SN            191
31             51
20             49
1              47
             ...
2699            1
1047            1
399             1
1082            1
365             1
Length: 1499, dtype: int64

Complemento
0                                     189
A                                      64
TERREO                                 56
POSTO                                  25
                                       22
                                     ...
LOTES 5B E 5C                           2
QUADRA132                 LOTE  01      1
QD.204                                  1
QUADRA 06, LOTE 16                      1
LOTES 07 E 08, QUADRA 18, SETOR 03      1
Length: 403, dtype: int64

Bairro
CENTRO                1613
ALDEOTA                 77
SANTO ANTONIO           52
JARDIM AMERICA          39
SERRARIA                38
                      ...
LARANJEIRA               1
AGENOR DE CARVALHO       1
SERINGAL                 1
INDEPENDENCIA            1
CIDADE NOVA I            1
Length: 1342, dtype: int64

Cep
17400-000    59
15200-000    43
78580-000    43
46430-000    41
92500-000    36
             ..
89051-000     1
68501-170     1
68501-130     1
68908-181     1
68908-015     1
Length: 2005, dtype: int64

Produto
GASOLINA              2502
ETANOL                2243
DIESEL S10            2025
GASOLINA ADITIVADA    1889
DIESEL                1094
GNV                    247
dtype: int64

Data da Coleta
05/07/2021        5202
04/07/2021        2178
01/07/2021        1380
06/07/2021        1240
dtype: int64

Valor de Venda
4.399             272
4.499             270
4.599             232
5.599             209
4.699             206
                 ...
5.097               1
5.094               1
5.092               1
5.070               1
5.130               1
Length: 910, dtype: int64

Series([], dtype: int64)

Unidade de Medida
R$ / litro           9753
R$ / m³               247
dtype: int64

Bandeira
BRANCA                  3532
VIBRA ENERGIA           2320
RAIZEN                  1706
IPIRANGA                1667
ALESAT                   227
SABBÁ                    111
RAIZEN MIME               58
ATEM' S                   52
RODOIL                    44
EQUADOR                   36
DISLUB                    26
IDAZA                     24
SP                        20
PETROX DISTRIBUIDORA      16
FAN                       12
CIAPETRO                  12
SIMARELLI                 12
FEDERAL ENERGIA           11
TEMAPE                    11
ATLÂNTICA                 11
PETROBAHIA                10
STANG                      9
TAURUS                     9
SETTA DISTRIBUIDORA        8
AMERICANOIL                6
WALENDOWSKY                5
ROYAL FIC                  5
MASUT DISTRIBUIDORA        5
ESTRADA                    5
D`MAIS                     5
RZD DISTRIBUIDORA          4
POTENCIAL                  4
SUL COMBUSTÍVEIS           4
PODIUM                     4
TDC DISTRIBUIDORA          3
TORRAO                     3
CHARRUA                    3
dtype: int64

In [8]:
df.columns

Index(['Regiao - Sigla', 'Estado - Sigla', 'Municipio', 'Revenda',
       'CNPJ da Revenda', 'Nome da Rua', 'Numero Rua', 'Complemento', 'Bairro',
       'Cep', 'Produto', 'Data da Coleta', 'Valor de Venda', 'Valor de Compra',
       'Unidade de Medida', 'Bandeira'],
      dtype='object')

In [9]:
df2 = pd.read_csv("entrada/ca-2022-01.csv.bz2", sep=";", nrows=10000, decimal=",",
                 usecols=['Regiao - Sigla', 'Estado - Sigla', 'Municipio', 'Bairro',
                          'Produto', 'Valor de Venda', 'Valor de Compra', 'Unidade de Medida',
                          'Data da Coleta', 'Bandeira', 'Revenda'],
                 parse_dates=['Data da Coleta'], dayfirst=True)
df2.head(5)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,Bairro,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,N,AC,RIO BRANCO,AUTO POSTO AMAPA - EIRELI,AREAL,GASOLINA,2022-01-03,6.99,NaN,R$ / litro,VIBRA ENERGIA
1,N,AC,RIO BRANCO,AUTO POSTO AMAPA - EIRELI,AREAL,ETANOL,2022-01-03,5.99,NaN,R$ / litro,VIBRA ENERGIA
2,N,AC,RIO BRANCO,AUTO POSTO AMAPA - EIRELI,AREAL,DIESEL,2022-01-03,6.09,NaN,R$ / litro,VIBRA ENERGIA
3,N,AC,RIO BRANCO,AUTO POSTO AMAPA - EIRELI,AREAL,GASOLINA ADITIVADA,2022-01-03,7.05,NaN,R$ / litro,VIBRA ENERGIA
4,N,AC,RIO BRANCO,AUTO POSTO AMAPA - EIRELI,AREAL,DIESEL S10,2022-01-03,6.12,NaN,R$ / litro,VIBRA ENERGIA

In [10]:
%%script echo
df2.rename({'Regiao - Sigla': 'Regiao', 'Estado - Sigla': 'UF', 
            'Valor de Venda': 'Venda', 'Valor de Compra': 'Compra',
            'Unidade de Medida': 'Unidade', 'Data da Coleta': 'Coleta'},
           axis=1, inplace=True)
df2.head(5)

In [11]:
%%script echo
ocols = df2.columns.tolist()
ocols

In [12]:
%%script echo
lcols = [col.lower() for col in ocols]
lcols

In [13]:
%%script echo
dict(zip(ocols, lcols))

In [14]:
df2.rename({'Regiao - Sigla': 'regiao', 'Estado - Sigla': 'uf',
            'Municipio': 'municipio', 'Bairro': 'bairro',
            'Produto': 'produto', 'Valor de Venda': 'venda', 
            'Valor de Compra': 'compra', 'Unidade de Medida': 'unidade',
            'Data da Coleta': 'coleta',
            'Bandeira': 'bandeira',
            'Revenda': 'revenda'},
           axis=1, inplace=True)
df2.head(5)

,regiao,uf,municipio,revenda,bairro,produto,coleta,venda,compra,unidade,bandeira
0,N,AC,RIO BRANCO,AUTO POSTO AMAPA - EIRELI,AREAL,GASOLINA,2022-01-03,6.99,NaN,R$ / litro,VIBRA ENERGIA
1,N,AC,RIO BRANCO,AUTO POSTO AMAPA - EIRELI,AREAL,ETANOL,2022-01-03,5.99,NaN,R$ / litro,VIBRA ENERGIA
2,N,AC,RIO BRANCO,AUTO POSTO AMAPA - EIRELI,AREAL,DIESEL,2022-01-03,6.09,NaN,R$ / litro,VIBRA ENERGIA
3,N,AC,RIO BRANCO,AUTO POSTO AMAPA - EIRELI,AREAL,GASOLINA ADITIVADA,2022-01-03,7.05,NaN,R$ / litro,VIBRA ENERGIA
4,N,AC,RIO BRANCO,AUTO POSTO AMAPA - EIRELI,AREAL,DIESEL S10,2022-01-03,6.12,NaN,R$ / litro,VIBRA ENERGIA

In [15]:
df2.columns

Index(['regiao', 'uf', 'municipio', 'revenda', 'bairro', 'produto', 'coleta',
       'venda', 'compra', 'unidade', 'bandeira'],
      dtype='object')

In [16]:
df3 = df2[['regiao', 'uf', 'municipio', 'bairro',
     'produto', 'venda', 'compra', 'unidade', 'coleta',
     'bandeira', 'revenda']]
df3.head()

,regiao,uf,municipio,bairro,produto,venda,compra,unidade,coleta,bandeira,revenda
0,N,AC,RIO BRANCO,AREAL,GASOLINA,6.99,NaN,R$ / litro,2022-01-03,VIBRA ENERGIA,AUTO POSTO AMAPA - EIRELI
1,N,AC,RIO BRANCO,AREAL,ETANOL,5.99,NaN,R$ / litro,2022-01-03,VIBRA ENERGIA,AUTO POSTO AMAPA - EIRELI
2,N,AC,RIO BRANCO,AREAL,DIESEL,6.09,NaN,R$ / litro,2022-01-03,VIBRA ENERGIA,AUTO POSTO AMAPA - EIRELI
3,N,AC,RIO BRANCO,AREAL,GASOLINA ADITIVADA,7.05,NaN,R$ / litro,2022-01-03,VIBRA ENERGIA,AUTO POSTO AMAPA - EIRELI
4,N,AC,RIO BRANCO,AREAL,DIESEL S10,6.12,NaN,R$ / litro,2022-01-03,VIBRA ENERGIA,AUTO POSTO AMAPA - EIRELI