In [1]:
import pandas as pd

In [2]:
# ler os dados do arquivo CSV
df = pd.read_csv("ge-2017-2022.csv.bz2",
                 dtype={'regiao': 'category', 'uf': 'category', 
                        'municipio': 'category', 'bairro': 'category',
                        'produto': 'category', 'venda': 'float32',
                        'compra': 'float32', 'unidade': 'category',
                        'ano': 'uint16', 'mes': 'uint8',
                        'bandeira': 'category'})

In [3]:
df

,regiao,uf,municipio,bairro,produto,venda,compra,ano,mes,bandeira,revenda
0,SE,SP,SOROCABA,JARDIM ZULMIRA,GASOLINA,3.110,NaN,2017,7,BRANCA,COMPETRO COMERCIO E DISTRIBUICAO DE DERIVADOS ...
1,SE,SP,SOROCABA,JARDIM ZULMIRA,ETANOL,2.020,NaN,2017,7,BRANCA,COMPETRO COMERCIO E DISTRIBUICAO DE DERIVADOS ...
2,NE,BA,ITABUNA,MANOEL LEAO,GASOLINA,3.599,NaN,2017,7,BRANCA,LOPES LEMOS COMERCIO DE COMBUSTIVEIS LTDA
3,S,PR,PATO BRANCO,CENTRO,GASOLINA,3.680,3.0396,2017,7,RODOIL,SANTOS & MERLO LTDA.
4,S,PR,PATO BRANCO,CENTRO,ETANOL,2.780,NaN,2017,7,RODOIL,SANTOS & MERLO LTDA.
...,...,...,...,...,...,...,...,...,...,...,...
2624163,CO,GO,APARECIDA DE GOIANIA,JARDIM HELVECIA,ETANOL,2.899,2.3550,2018,6,RIO BRANCO,RE AUTO POSTO LTDA
2624164,SE,MG,JUIZ DE FORA,INDUSTRIAL,ETANOL,2.960,2.2850,2018,6,BRANCA,POSTO FACIT LTDA
2624165,NE,PI,PARNAIBA,SAO BENEDITO,GASOLINA,4.850,NaN,2018,6,PETROBRAS DISTRIBUIDORA S.A.,V. MACHADO & CIA LTDA
2624166,NE,BA,BARREIRAS,CENTRO,GASOLINA,4.599,NaN,2018,6,PETROBRAS DISTRIBUIDORA S.A.,POSTO MACAUBENSE LTDA
2624167,NE,BA,BARREIRAS,CENTRO,ETANOL,3.049,NaN,2018,6,PETROBRAS DISTRIBUIDORA S.A.,POSTO MACAUBENSE LTDA

In [4]:
# selecionar apenas linhas que possuem valor de compra preenchido
df2 = df[~df['compra'].isna()]
df2

,regiao,uf,municipio,bairro,produto,venda,compra,ano,mes,bandeira,revenda
3,S,PR,PATO BRANCO,CENTRO,GASOLINA,3.680,3.0396,2017,7,RODOIL,SANTOS & MERLO LTDA.
9,N,AC,CRUZEIRO DO SUL,JOÃƒÂƒO ALVES,GASOLINA,4.700,3.5757,2017,7,BRANCA,CARDINAL E OLIVEIRA LTDA
13,N,AC,RIO BRANCO,ESTACAO EXPERIMENTAL,GASOLINA,3.830,3.2829,2017,7,PETROBRAS DISTRIBUIDORA S.A.,AUTO POSTO ISAURAO LTDA
14,N,AC,RIO BRANCO,ESTACAO EXPERIMENTAL,ETANOL,3.600,3.0056,2017,7,PETROBRAS DISTRIBUIDORA S.A.,AUTO POSTO ISAURAO LTDA
15,N,AC,RIO BRANCO,AVIARIO,GASOLINA,3.850,3.4399,2017,7,PETROBRAS DISTRIBUIDORA S.A.,COMDEPE COMERCIO DE DERIVADOS DE PETROLEO LTDA
...,...,...,...,...,...,...,...,...,...,...,...
2624158,NE,AL,ARAPIRACA,PRIMAVERA,GASOLINA,4.620,4.1984,2018,6,ALESAT,POSTO ARAPIRACA LTDA
2624159,NE,AL,ARAPIRACA,PRIMAVERA,ETANOL,3.599,3.2469,2018,6,ALESAT,POSTO ARAPIRACA LTDA
2624162,CO,GO,APARECIDA DE GOIANIA,JARDIM HELVECIA,GASOLINA,4.799,4.2698,2018,6,RIO BRANCO,RE AUTO POSTO LTDA
2624163,CO,GO,APARECIDA DE GOIANIA,JARDIM HELVECIA,ETANOL,2.899,2.3550,2018,6,RIO BRANCO,RE AUTO POSTO LTDA
2624164,SE,MG,JUIZ DE FORA,INDUSTRIAL,ETANOL,2.960,2.2850,2018,6,BRANCA,POSTO FACIT LTDA

In [5]:
# remover colunas que serÃ£o desprezadas
df2r = df2.drop(['regiao', 'municipio', 'bairro', 'bandeira', 'revenda'], axis=1)
#df2r = df2.drop(['uf', 'municipio', 'bairro', 'bandeira', 'revenda'], axis=1)
df2r

         uf   produto  venda  compra   ano  mes
3        PR  GASOLINA  3.680  3.0396  2017    7
9        AC  GASOLINA  4.700  3.5757  2017    7
13       AC  GASOLINA  3.830  3.2829  2017    7
14       AC    ETANOL  3.600  3.0056  2017    7
15       AC  GASOLINA  3.850  3.4399  2017    7
...      ..       ...    ...     ...   ...  ...
2624158  AL  GASOLINA  4.620  4.1984  2018    6
2624159  AL    ETANOL  3.599  3.2469  2018    6
2624162  GO  GASOLINA  4.799  4.2698  2018    6
2624163  GO    ETANOL  2.899  2.3550  2018    6
2624164  MG    ETANOL  2.960  2.2850  2018    6

[762000 rows x 6 columns]

In [6]:
df2r.describe(include='all')

,uf,produto,venda,compra,ano,mes
count,762000,762000,762000.000000,762000.000000,762000.000000,762000.000000
unique,27,2,NaN,NaN,NaN,NaN
top,SP,GASOLINA,NaN,NaN,NaN,NaN
freq,278621,419178,NaN,NaN,NaN,NaN
mean,NaN,NaN,3.697169,3.238269,2018.265829,5.902588
std,NaN,NaN,0.747269,0.689781,0.994811,3.387604
min,NaN,NaN,1.780000,1.555300,2017.000000,1.000000
25%,NaN,NaN,2.999000,2.639175,2017.000000,3.000000
50%,NaN,NaN,3.779000,3.269900,2018.000000,6.000000
75%,NaN,NaN,4.299000,3.815000,2019.000000,9.000000
max,NaN,NaN,5.799000,5.091000,2020.000000,12.000000

In [7]:
df2r.corr()

           venda    compra       ano       mes
venda   1.000000  0.970187  0.219366  0.042175
compra  0.970187  1.000000  0.235280  0.042502
ano     0.219366  0.235280  1.000000 -0.075279
mes     0.042175  0.042502 -0.075279  1.000000

In [8]:
# converter colunas categÃ³ricas em numÃ©ricas (one-hot encoding)
df2r = pd.get_dummies(df2r)
df2r

,venda,compra,ano,mes,uf_AC,uf_AL,uf_AM,uf_AP,uf_BA,uf_CE,...,uf_RN,uf_RO,uf_RR,uf_RS,uf_SC,uf_SE,uf_SP,uf_TO,produto_ETANOL,produto_GASOLINA
3,3.680,3.0396,2017,7,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9,4.700,3.5757,2017,7,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13,3.830,3.2829,2017,7,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
14,3.600,3.0056,2017,7,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
15,3.850,3.4399,2017,7,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2624158,4.620,4.1984,2018,6,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2624159,3.599,3.2469,2018,6,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2624162,4.799,4.2698,2018,6,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2624163,2.899,2.3550,2018,6,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2624164,2.960,2.2850,2018,6,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [9]:
df2r.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 762000 entries, 3 to 2624164
Data columns (total 33 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   venda             762000 non-null  float32
 1   compra            762000 non-null  float32
 2   ano               762000 non-null  uint16
 3   mes               762000 non-null  uint8
 4   uf_AC             762000 non-null  uint8
 5   uf_AL             762000 non-null  uint8
 6   uf_AM             762000 non-null  uint8
 7   uf_AP             762000 non-null  uint8
 8   uf_BA             762000 non-null  uint8
 9   uf_CE             762000 non-null  uint8
 10  uf_DF             762000 non-null  uint8
 11  uf_ES             762000 non-null  uint8
 12  uf_GO             762000 non-null  uint8
 13  uf_MA             762000 non-null  uint8
 14  uf_MG             762000 non-null  uint8
 15  uf_MS             762000 non-null  uint8
 16  uf_MT             762000 non-null  uint8
 17  uf_PA             762000 non-null  uint8
 18  uf_PB             762000 non-null  uint8
 19  uf_PE             762000 non-null  uint8
 20  uf_PI             762000 non-null  uint8
 21  uf_PR             762000 non-null  uint8
 22  uf_RJ             762000 non-null  uint8
 23  uf_RN             762000 non-null  uint8
 24  uf_RO             762000 non-null  uint8
 25  uf_RR             762000 non-null  uint8
 26  uf_RS             762000 non-null  uint8
 27  uf_SC             762000 non-null  uint8
 28  uf_SE             762000 non-null  uint8
 29  uf_SP             762000 non-null  uint8
 30  uf_TO             762000 non-null  uint8
 31  produto_ETANOL    762000 non-null  uint8
 32  produto_GASOLINA  762000 non-null  uint8
dtypes: float32(2), uint16(1), uint8(30)
memory usage: 34.9 MB

In [10]:
df2r.corr()

,venda,compra,ano,mes,uf_AC,uf_AL,uf_AM,uf_AP,uf_BA,uf_CE,...,uf_RN,uf_RO,uf_RR,uf_RS,uf_SC,uf_SE,uf_SP,uf_TO,produto_ETANOL,produto_GASOLINA
venda,1.000000,0.970187,0.219366,0.042175,0.072478,0.039259,0.060315,0.013092,0.050283,0.092785,...,0.041556,0.055735,0.023740,0.167483,0.043961,0.015044,-0.359639,0.041230,-0.792096,0.792096
compra,0.970187,1.000000,0.235280,0.042502,0.056853,0.032563,0.038346,0.026158,0.006757,0.087983,...,0.041443,0.042932,0.021419,0.158501,0.059607,0.021215,-0.343915,0.037650,-0.795472,0.795472
ano,0.219366,0.235280,1.000000,-0.075279,-0.014650,0.004037,-0.003733,0.005546,0.026086,-0.009866,...,-0.004273,0.001424,0.012842,-0.014018,0.014789,-0.005436,-0.000928,0.017117,0.006968,-0.006968
mes,0.042175,0.042502,-0.075279,1.000000,0.004242,-0.003190,0.004103,-0.001459,-0.000096,-0.001247,...,0.005449,0.000224,0.003501,0.001620,0.002845,0.003471,-0.000710,0.006398,0.004514,-0.004514
uf_AC,0.072478,0.056853,-0.014650,0.004242,1.000000,-0.007371,-0.008372,-0.002998,-0.021222,-0.011198,...,-0.005854,-0.005161,-0.004178,-0.013393,-0.009686,-0.005579,-0.052059,-0.005046,-0.021658,0.021658
uf_AL,0.039259,0.032563,0.004037,-0.003190,-0.007371,1.000000,-0.013125,-0.004700,-0.033268,-0.017554,...,-0.009176,-0.008091,-0.006549,-0.020995,-0.015183,-0.008746,-0.081609,-0.007911,-0.003746,0.003746
uf_AM,0.060315,0.038346,-0.003733,0.004103,-0.008372,-0.013125,1.000000,-0.005339,-0.037788,-0.019939,...,-0.010423,-0.009190,-0.007439,-0.023847,-0.017247,-0.009934,-0.092698,-0.008986,-0.025561,0.025561
uf_AP,0.013092,0.026158,0.005546,-0.001459,-0.002998,-0.004700,-0.005339,1.000000,-0.013532,-0.007140,...,-0.003733,-0.003291,-0.002664,-0.008540,-0.006176,-0.003557,-0.033196,-0.003218,-0.037849,0.037849
uf_BA,0.050283,0.006757,0.026086,-0.000096,-0.021222,-0.033268,-0.037788,-0.013532,1.000000,-0.050540,...,-0.026420,-0.023296,-0.018856,-0.060447,-0.043716,-0.025180,-0.234968,-0.022777,0.023235,-0.023235
uf_CE,0.092785,0.087983,-0.009866,-0.001247,-0.011198,-0.017554,-0.019939,-0.007140,-0.050540,1.000000,...,-0.013941,-0.012292,-0.009949,-0.031895,-0.023067,-0.013287,-0.123981,-0.012018,-0.049154,0.049154
uf_DF,0.014093,0.025283,0.006586,0.012579,-0.005570,-0.008733,-0.009919,-0.003552,-0.025142,-0.013266,...,-0.006935,-0.006115,-0.004949,-0.015867,-0.011475,-0.006610,-0.061677,-0.005979,-0.001722,0.001722
uf_ES,0.068085,0.078021,-0.011779,0.002556,-0.008671,-0.013593,-0.015440,-0.005529,-0.039138,-0.020651,...,-0.010796,-0.009519,-0.007705,-0.024699,-0.017863,-0.010289,-0.096009,-0.009307,-0.071848,0.071848
uf_GO,-0.007278,-0.006425,-0.005904,-0.002034,-0.010052,-0.015757,-0.017898,-0.006410,-0.045368,-0.023939,...,-0.012514,-0.011034,-0.008931,-0.028631,-0.020706,-0.011927,-0.111293,-0.010788,0.016326,-0.016326
uf_MA,0.033901,0.029229,-0.016172,-0.009533,-0.006373,-0.009990,-0.011347,-0.004063,-0.028762,-0.015177,...,-0.007934,-0.006995,-0.005662,-0.018151,-0.013127,-0.007561,-0.070558,-0.006840,-0.045882,0.045882
uf_MG,0.013305,0.014854,-0.006844,-0.009885,-0.021806,-0.034184,-0.038829,-0.013905,-0.098422,-0.051933,...,-0.027148,-0.023937,-0.019375,-0.062113,-0.044920,-0.025874,-0.241441,-0.023405,0.027908,-0.027908
uf_MS,-0.007183,0.006944,-0.016057,0.000475,-0.009299,-0.014577,-0.016558,-0.005929,-0.041969,-0.022145,...,-0.011577,-0.010207,-0.008262,-0.026486,-0.019155,-0.011033,-0.102956,-0.009980,0.009378,-0.009378
uf_MT,-0.034738,-0.039039,-0.008325,-0.001531,-0.008720,-0.013670,-0.015527,-0.005560,-0.039358,-0.020767,...,-0.010856,-0.009572,-0.007748,-0.024838,-0.017963,-0.010347,-0.096549,-0.009359,0.014251,-0.014251
uf_PA,0.091753,0.078406,-0.009280,-0.004775,-0.007439,-0.011662,-0.013246,-0.004743,-0.033576,-0.017716,...,-0.009261,-0.008166,-0.006610,-0.021189,-0.015324,-0.008827,-0.082365,-0.007984,-0.057222,0.057222
uf_PB,-0.003323,0.009634,-0.001917,0.004037,-0.007224,-0.011324,-0.012863,-0.004606,-0.032604,-0.017204,...,-0.008993,-0.007930,-0.006418,-0.020576,-0.014881,-0.008571,-0.079981,-0.007753,0.005242,-0.005242
uf_PE,0.017165,0.022234,-0.013643,0.003379,-0.013010,-0.020396,-0.023167,-0.008296,-0.058723,-0.030985,...,-0.016198,-0.014282,-0.011560,-0.037059,-0.026801,-0.015438,-0.144054,-0.013964,-0.002309,0.002309
uf_PI,0.028310,0.027340,-0.000211,-0.008095,-0.004654,-0.007296,-0.008287,-0.002968,-0.021005,-0.011083,...,-0.005794,-0.005109,-0.004135,-0.013256,-0.009587,-0.005522,-0.051528,-0.004995,-0.019326,0.019326
uf_PR,-0.059219,-0.040479,-0.006979,-0.003336,-0.016920,-0.026524,-0.030128,-0.010789,-0.076367,-0.040295,...,-0.021065,-0.018573,-0.015033,-0.048194,-0.034854,-0.020076,-0.187337,-0.018160,0.020206,-0.020206
uf_RJ,0.211883,0.215022,0.027366,0.005396,-0.023659,-0.037088,-0.042128,-0.015086,-0.106783,-0.056344,...,-0.029454,-0.025971,-0.021021,-0.067389,-0.048736,-0.028072,-0.261952,-0.025393,0.019498,-0.019498
uf_RN,0.041556,0.041443,-0.004273,0.005449,-0.005854,-0.009176,-0.010423,-0.003733,-0.026420,-0.013941,...,1.000000,-0.006426,-0.005201,-0.016673,-0.012058,-0.006946,-0.064812,-0.006283,-0.028801,0.028801
uf_RO,0.055735,0.042932,0.001424,0.000224,-0.005161,-0.008091,-0.009190,-0.003291,-0.023296,-0.012292,...,-0.006426,1.000000,-0.004586,-0.014701,-0.010632,-0.006124,-0.057147,-0.005540,-0.031664,0.031664
uf_RR,0.023740,0.021419,0.012842,0.003501,-0.004178,-0.006549,-0.007439,-0.002664,-0.018856,-0.009949,...,-0.005201,-0.004586,1.000000,-0.011899,-0.008606,-0.004957,-0.046255,-0.004484,-0.029805,0.029805
uf_RS,0.167483,0.158501,-0.014018,0.001620,-0.013393,-0.020995,-0.023847,-0.008540,-0.060447,-0.031895,...,-0.016673,-0.014701,-0.011899,1.000000,-0.027588,-0.015891,-0.148284,-0.014374,-0.085926,0.085926
uf_SC,0.043961,0.059607,0.014789,0.002845,-0.009686,-0.015183,-0.017247,-0.006176,-0.043716,-0.023067,...,-0.012058,-0.010632,-0.008606,-0.027588,1.000000,-0.011492,-0.107240,-0.010395,-0.070596,0.070596
uf_SE,0.015044,0.021215,-0.005436,0.003471,-0.005579,-0.008746,-0.009934,-0.003557,-0.025180,-0.013287,...,-0.006946,-0.006124,-0.004957,-0.015891,-0.011492,1.000000,-0.061770,-0.005988,-0.001516,0.001516
uf_SP,-0.359639,-0.343915,-0.000928,-0.000710,-0.052059,-0.081609,-0.092698,-0.033196,-0.234968,-0.123981,...,-0.064812,-0.057147,-0.046255,-0.148284,-0.107240,-0.061770,1.000000,-0.055875,0.077582,-0.077582
uf_TO,0.041230,0.037650,0.017117,0.006398,-0.005046,-0.007911,-0.008986,-0.003218,-0.022777,-0.012018,...,-0.006283,-0.005540,-0.004484,-0.014374,-0.010395,-0.005988,-0.055875,1.000000,-0.004643,0.004643
produto_ETANOL,-0.792096,-0.795472,0.006968,0.004514,-0.021658,-0.003746,-0.025561,-0.037849,0.023235,-0.049154,...,-0.028801,-0.031664,-0.029805,-0.085926,-0.070596,-0.001516,0.077582,-0.004643,1.000000,-1.000000
produto_GASOLINA,0.792096,0.795472,-0.006968,-0.004514,0.021658,0.003746,0.025561,0.037849,-0.023235,0.049154,...,0.028801,0.031664,0.029805,0.085926,0.070596,0.001516,-0.077582,0.004643,-1.000000,1.000000

## Treinar modelo de regressÃ£o

In [11]:
from sklearn.ensemble import RandomForestRegressor

In [12]:
X = df2r.drop('compra', axis=1).values
y = df2r['compra']

In [13]:
X.shape, y.shape

((762000, 32), (762000,))

In [14]:
modelo = RandomForestRegressor(random_state=42, n_jobs=-1)
modelo

RandomForestRegressor(n_jobs=-1, random_state=42)

In [16]:
%time modelo.fit(X, y)

CPU times: user 8min 42s, sys: 1.04 s, total: 8min 43s
Wall time: 45.3 s

RandomForestRegressor(n_jobs=-1, random_state=42)

In [17]:
X[0]

array([3.680e+00, 2.017e+03, 7.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 1.000e+00], dtype=float32)

In [18]:
modelo.predict([X[0]])

array([3.03274614])

## Imputar valores ausentes

In [19]:
# selecionar apenas linhas que nÃ£o possuem valor de compra preenchido
df3 = df[df['compra'].isna()]
df3

,regiao,uf,municipio,bairro,produto,venda,compra,ano,mes,bandeira,revenda
0,SE,SP,SOROCABA,JARDIM ZULMIRA,GASOLINA,3.110,NaN,2017,7,BRANCA,COMPETRO COMERCIO E DISTRIBUICAO DE DERIVADOS ...
1,SE,SP,SOROCABA,JARDIM ZULMIRA,ETANOL,2.020,NaN,2017,7,BRANCA,COMPETRO COMERCIO E DISTRIBUICAO DE DERIVADOS ...
2,NE,BA,ITABUNA,MANOEL LEAO,GASOLINA,3.599,NaN,2017,7,BRANCA,LOPES LEMOS COMERCIO DE COMBUSTIVEIS LTDA
4,S,PR,PATO BRANCO,CENTRO,ETANOL,2.780,NaN,2017,7,RODOIL,SANTOS & MERLO LTDA.
5,N,AC,CRUZEIRO DO SUL,CENTRO,GASOLINA,4.700,NaN,2017,7,PETROBRAS DISTRIBUIDORA S.A.,CARDINAL E OLIVEIRA LTDA
...,...,...,...,...,...,...,...,...,...,...,...
2624160,SE,MG,MANHUACU,REALEZA,GASOLINA,4.790,NaN,2018,6,RAIZEN,AUTO POSTO NAZARAO REALEZA LTDA
2624161,SE,MG,MANHUACU,REALEZA,ETANOL,2.990,NaN,2018,6,RAIZEN,AUTO POSTO NAZARAO REALEZA LTDA
2624165,NE,PI,PARNAIBA,SAO BENEDITO,GASOLINA,4.850,NaN,2018,6,PETROBRAS DISTRIBUIDORA S.A.,V. MACHADO & CIA LTDA
2624166,NE,BA,BARREIRAS,CENTRO,GASOLINA,4.599,NaN,2018,6,PETROBRAS DISTRIBUIDORA S.A.,POSTO MACAUBENSE LTDA
2624167,NE,BA,BARREIRAS,CENTRO,ETANOL,3.049,NaN,2018,6,PETROBRAS DISTRIBUIDORA S.A.,POSTO MACAUBENSE LTDA

In [20]:
# remover colunas que serÃ£o desprezadas
df3r = df3.drop(['regiao', 'municipio', 'bairro', 'bandeira', 'revenda', 'compra'], axis=1)
#df3r = df3.drop(['uf', 'municipio', 'bairro', 'bandeira', 'revenda', 'compra'], axis=1)
df3r

         uf   produto  venda   ano  mes
0        SP  GASOLINA  3.110  2017    7
1        SP    ETANOL  2.020  2017    7
2        BA  GASOLINA  3.599  2017    7
4        PR    ETANOL  2.780  2017    7
5        AC  GASOLINA  4.700  2017    7
...      ..       ...    ...   ...  ...
2624160  MG  GASOLINA  4.790  2018    6
2624161  MG    ETANOL  2.990  2018    6
2624165  PI  GASOLINA  4.850  2018    6
2624166  BA  GASOLINA  4.599  2018    6
2624167  BA    ETANOL  3.049  2018    6

[1862168 rows x 5 columns]

In [21]:
# converter colunas categÃ³ricas em numÃ©ricas (one-hot encoding)
df3r = pd.get_dummies(df3r)
df3r

,venda,ano,mes,uf_AC,uf_AL,uf_AM,uf_AP,uf_BA,uf_CE,uf_DF,...,uf_RN,uf_RO,uf_RR,uf_RS,uf_SC,uf_SE,uf_SP,uf_TO,produto_ETANOL,produto_GASOLINA
0,3.110,2017,7,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
1,2.020,2017,7,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
2,3.599,2017,7,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
4,2.780,2017,7,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
5,4.700,2017,7,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2624160,4.790,2018,6,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2624161,2.990,2018,6,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2624165,4.850,2018,6,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2624166,4.599,2018,6,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
2624167,3.049,2018,6,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0

In [22]:
df3r.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1862168 entries, 0 to 2624167
Data columns (total 32 columns):
 #   Column            Dtype
---  ------            -----
 0   venda             float32
 1   ano               uint16
 2   mes               uint8
 3   uf_AC             uint8
 4   uf_AL             uint8
 5   uf_AM             uint8
 6   uf_AP             uint8
 7   uf_BA             uint8
 8   uf_CE             uint8
 9   uf_DF             uint8
 10  uf_ES             uint8
 11  uf_GO             uint8
 12  uf_MA             uint8
 13  uf_MG             uint8
 14  uf_MS             uint8
 15  uf_MT             uint8
 16  uf_PA             uint8
 17  uf_PB             uint8
 18  uf_PE             uint8
 19  uf_PI             uint8
 20  uf_PR             uint8
 21  uf_RJ             uint8
 22  uf_RN             uint8
 23  uf_RO             uint8
 24  uf_RR             uint8
 25  uf_RS             uint8
 26  uf_SC             uint8
 27  uf_SE             uint8
 28  uf_SP             uint8
 29  uf_TO             uint8
 30  produto_ETANOL    uint8
 31  produto_GASOLINA  uint8
dtypes: float32(1), uint16(1), uint8(30)
memory usage: 78.1 MB

In [23]:
df3r.corr()

,venda,ano,mes,uf_AC,uf_AL,uf_AM,uf_AP,uf_BA,uf_CE,uf_DF,...,uf_RN,uf_RO,uf_RR,uf_RS,uf_SC,uf_SE,uf_SP,uf_TO,produto_ETANOL,produto_GASOLINA
venda,1.000000,0.676109,0.025015,0.052616,0.017416,0.025181,0.000548,0.046037,0.034267,0.009682,...,0.013562,0.025086,0.026782,0.084610,-0.004728,0.015695,-0.142673,0.014678,-0.493548,0.493548
ano,0.676109,1.000000,-0.108081,0.008380,0.002535,0.020863,0.004759,0.014899,-0.009080,0.007330,...,-0.008525,-0.018232,0.026938,-0.029477,-0.037055,0.010072,0.068438,-0.015996,-0.015146,0.015146
mes,0.025015,-0.108081,1.000000,0.002571,0.000393,0.001825,0.001438,-0.001754,0.006341,0.000832,...,0.000264,0.000157,0.002510,-0.007524,-0.003707,-0.001479,0.003311,-0.002952,-0.001575,0.001575
uf_AC,0.052616,0.008380,0.002571,1.000000,-0.007846,-0.007499,-0.004201,-0.016943,-0.016926,-0.007772,...,-0.008901,-0.008122,-0.002105,-0.018500,-0.016964,-0.006556,-0.049210,-0.006951,-0.020590,0.020590
uf_AL,0.017416,0.002535,0.000393,-0.007846,1.000000,-0.009748,-0.005461,-0.022024,-0.022002,-0.010103,...,-0.011571,-0.010557,-0.002736,-0.024048,-0.022051,-0.008523,-0.063966,-0.009035,0.005873,-0.005873
uf_AM,0.025181,0.020863,0.001825,-0.007499,-0.009748,1.000000,-0.005219,-0.021051,-0.021030,-0.009656,...,-0.011059,-0.010091,-0.002615,-0.022986,-0.021077,-0.008146,-0.061141,-0.008636,-0.021205,0.021205
uf_AP,0.000548,0.004759,0.001438,-0.004201,-0.005461,-0.005219,1.000000,-0.011793,-0.011781,-0.005410,...,-0.006196,-0.005653,-0.001465,-0.012877,-0.011807,-0.004563,-0.034251,-0.004838,-0.047760,0.047760
uf_BA,0.046037,0.014899,-0.001754,-0.016943,-0.022024,-0.021051,-0.011793,1.000000,-0.047514,-0.021817,...,-0.024987,-0.022799,-0.005909,-0.051933,-0.047620,-0.018405,-0.138139,-0.019512,0.010321,-0.010321
uf_CE,0.034267,-0.009080,0.006341,-0.016926,-0.022002,-0.021030,-0.011781,-0.047514,1.000000,-0.021796,...,-0.024963,-0.022777,-0.005903,-0.051882,-0.047573,-0.018387,-0.138003,-0.019493,0.018744,-0.018744
uf_DF,0.009682,0.007330,0.000832,-0.007772,-0.010103,-0.009656,-0.005410,-0.021817,-0.021796,1.000000,...,-0.011462,-0.010458,-0.002711,-0.023823,-0.021844,-0.008443,-0.063367,-0.008951,0.003823,-0.003823
uf_ES,0.025899,0.003129,-0.004355,-0.010511,-0.013663,-0.013059,-0.007316,-0.029505,-0.029476,-0.013535,...,-0.015501,-0.014144,-0.003666,-0.032217,-0.029542,-0.011418,-0.085696,-0.012104,-0.001531,0.001531
uf_GO,-0.035380,-0.040257,-0.001477,-0.017365,-0.022572,-0.021575,-0.012087,-0.048746,-0.048698,-0.022361,...,-0.025610,-0.023367,-0.006056,-0.053228,-0.048807,-0.018864,-0.141581,-0.019998,0.010626,-0.010626
uf_MA,0.008292,-0.018177,0.000003,-0.010522,-0.013677,-0.013073,-0.007323,-0.029536,-0.029507,-0.013549,...,-0.015517,-0.014159,-0.003669,-0.032251,-0.029573,-0.011430,-0.085786,-0.012117,-0.038938,0.038938
uf_MG,-0.005404,-0.028616,-0.002322,-0.027038,-0.035146,-0.033593,-0.018819,-0.075899,-0.075825,-0.034817,...,-0.039875,-0.036384,-0.009429,-0.082877,-0.075993,-0.029371,-0.220445,-0.031138,0.017518,-0.017518
uf_MS,0.004065,0.007042,0.003635,-0.009466,-0.012304,-0.011761,-0.006589,-0.026572,-0.026546,-0.012189,...,-0.013960,-0.012738,-0.003301,-0.029015,-0.026605,-0.010283,-0.077178,-0.010901,0.006027,-0.006027
uf_MT,-0.046844,-0.011852,0.007464,-0.014844,-0.019295,-0.018443,-0.010332,-0.041669,-0.041628,-0.019114,...,-0.021891,-0.019975,-0.005177,-0.045499,-0.041720,-0.016125,-0.121024,-0.017095,0.008285,-0.008285
uf_PA,0.054868,-0.004738,-0.003115,-0.009661,-0.012558,-0.012004,-0.006725,-0.027121,-0.027094,-0.012441,...,-0.014248,-0.013001,-0.003369,-0.029614,-0.027154,-0.010495,-0.078771,-0.011126,-0.040525,0.040525
uf_PB,-0.003069,0.005749,0.001699,-0.008370,-0.010880,-0.010399,-0.005826,-0.023496,-0.023472,-0.010778,...,-0.012344,-0.011263,-0.002919,-0.025655,-0.023525,-0.009092,-0.068241,-0.009639,0.003230,-0.003230
uf_PE,0.013029,0.009200,-0.000664,-0.014338,-0.018638,-0.017814,-0.009980,-0.040249,-0.040209,-0.018463,...,-0.021146,-0.019294,-0.005000,-0.043949,-0.040299,-0.015575,-0.116901,-0.016512,0.004129,-0.004129
uf_PI,0.015727,-0.012049,0.002481,-0.009062,-0.011779,-0.011259,-0.006307,-0.025437,-0.025412,-0.011669,...,-0.013364,-0.012194,-0.003160,-0.027776,-0.025469,-0.009844,-0.073881,-0.010436,-0.009407,0.009407
uf_PR,-0.056016,-0.015063,-0.002979,-0.021431,-0.027858,-0.026627,-0.014917,-0.060160,-0.060101,-0.027597,...,-0.031606,-0.028839,-0.007474,-0.065691,-0.060235,-0.023280,-0.174732,-0.024681,0.015902,-0.015902
uf_RJ,0.124110,0.022589,0.001321,-0.019779,-0.025710,-0.024575,-0.013767,-0.055523,-0.055469,-0.025470,...,-0.029170,-0.026616,-0.006898,-0.060627,-0.055592,-0.021486,-0.161264,-0.022779,0.013974,-0.013974
uf_RN,0.013562,-0.008525,0.000264,-0.008901,-0.011571,-0.011059,-0.006196,-0.024987,-0.024963,-0.011462,...,1.000000,-0.011978,-0.003104,-0.027284,-0.025018,-0.009669,-0.072574,-0.010251,0.014022,-0.014022
uf_RO,0.025086,-0.018232,0.000157,-0.008122,-0.010557,-0.010091,-0.005653,-0.022799,-0.022777,-0.010458,...,-0.011978,1.000000,-0.002832,-0.024895,-0.022828,-0.008823,-0.066219,-0.009353,-0.029762,0.029762
uf_RR,0.026782,0.026938,0.002510,-0.002105,-0.002736,-0.002615,-0.001465,-0.005909,-0.005903,-0.002711,...,-0.003104,-0.002832,1.000000,-0.006452,-0.005916,-0.002287,-0.017162,-0.002424,-0.016678,0.016678
uf_RS,0.084610,-0.029477,-0.007524,-0.018500,-0.024048,-0.022986,-0.012877,-0.051933,-0.051882,-0.023823,...,-0.027284,-0.024895,-0.006452,1.000000,-0.051998,-0.020097,-0.150838,-0.021306,-0.068725,0.068725
uf_SC,-0.004728,-0.037055,-0.003707,-0.016964,-0.022051,-0.021077,-0.011807,-0.047620,-0.047573,-0.021844,...,-0.025018,-0.022828,-0.005916,-0.051998,1.000000,-0.018428,-0.138310,-0.019536,-0.019306,0.019306
uf_SE,0.015695,0.010072,-0.001479,-0.006556,-0.008523,-0.008146,-0.004563,-0.018405,-0.018387,-0.008443,...,-0.009669,-0.008823,-0.002287,-0.020097,-0.018428,1.000000,-0.053456,-0.007551,-0.006572,0.006572
uf_SP,-0.142673,0.068438,0.003311,-0.049210,-0.063966,-0.061141,-0.034251,-0.138139,-0.138003,-0.063367,...,-0.072574,-0.066219,-0.017162,-0.150838,-0.138310,-0.053456,1.000000,-0.056672,0.031798,-0.031798
uf_TO,0.014678,-0.015996,-0.002952,-0.006951,-0.009035,-0.008636,-0.004838,-0.019512,-0.019493,-0.008951,...,-0.010251,-0.009353,-0.002424,-0.021306,-0.019536,-0.007551,-0.056672,1.000000,-0.002379,0.002379
produto_ETANOL,-0.493548,-0.015146,-0.001575,-0.020590,0.005873,-0.021205,-0.047760,0.010321,0.018744,0.003823,...,0.014022,-0.029762,-0.016678,-0.068725,-0.019306,-0.006572,0.031798,-0.002379,1.000000,-1.000000
produto_GASOLINA,0.493548,0.015146,0.001575,0.020590,-0.005873,0.021205,0.047760,-0.010321,-0.018744,-0.003823,...,-0.014022,0.029762,0.016678,0.068725,0.019306,0.006572,-0.031798,0.002379,-1.000000,1.000000

In [24]:
X3 = df3r.values
X3

array([[3.110e+00, 2.017e+03, 7.000e+00, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [2.020e+00, 2.017e+03, 7.000e+00, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [3.599e+00, 2.017e+03, 7.000e+00, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       ...,
       [4.850e+00, 2.018e+03, 6.000e+00, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [4.599e+00, 2.018e+03, 6.000e+00, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [3.049e+00, 2.018e+03, 6.000e+00, ..., 0.000e+00, 1.000e+00,
        0.000e+00]], dtype=float32)

In [25]:
y3_pred = modelo.predict(X3)
y3_pred

array([2.72932435, 1.78139817, 3.04129738, ..., 4.24546158, 4.03719263,
       2.55841136])

In [28]:
# imputar os valores ausentes
df3['compra'] = y3_pred
df3

<ipython-input-28-c82ea7d461da>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['compra'] = y3_pred

,regiao,uf,municipio,bairro,produto,venda,compra,ano,mes,bandeira,revenda
0,SE,SP,SOROCABA,JARDIM ZULMIRA,GASOLINA,3.110,2.729324,2017,7,BRANCA,COMPETRO COMERCIO E DISTRIBUICAO DE DERIVADOS ...
1,SE,SP,SOROCABA,JARDIM ZULMIRA,ETANOL,2.020,1.781398,2017,7,BRANCA,COMPETRO COMERCIO E DISTRIBUICAO DE DERIVADOS ...
2,NE,BA,ITABUNA,MANOEL LEAO,GASOLINA,3.599,3.041297,2017,7,BRANCA,LOPES LEMOS COMERCIO DE COMBUSTIVEIS LTDA
4,S,PR,PATO BRANCO,CENTRO,ETANOL,2.780,2.180255,2017,7,RODOIL,SANTOS & MERLO LTDA.
5,N,AC,CRUZEIRO DO SUL,CENTRO,GASOLINA,4.700,3.556995,2017,7,PETROBRAS DISTRIBUIDORA S.A.,CARDINAL E OLIVEIRA LTDA
...,...,...,...,...,...,...,...,...,...,...,...
2624160,SE,MG,MANHUACU,REALEZA,GASOLINA,4.790,4.298059,2018,6,RAIZEN,AUTO POSTO NAZARAO REALEZA LTDA
2624161,SE,MG,MANHUACU,REALEZA,ETANOL,2.990,2.608998,2018,6,RAIZEN,AUTO POSTO NAZARAO REALEZA LTDA
2624165,NE,PI,PARNAIBA,SAO BENEDITO,GASOLINA,4.850,4.245462,2018,6,PETROBRAS DISTRIBUIDORA S.A.,V. MACHADO & CIA LTDA
2624166,NE,BA,BARREIRAS,CENTRO,GASOLINA,4.599,4.037193,2018,6,PETROBRAS DISTRIBUIDORA S.A.,POSTO MACAUBENSE LTDA
2624167,NE,BA,BARREIRAS,CENTRO,ETANOL,3.049,2.558411,2018,6,PETROBRAS DISTRIBUIDORA S.A.,POSTO MACAUBENSE LTDA

In [29]:
df3.corr()

           venda    compra       ano       mes
venda   1.000000  0.812870  0.676109  0.025015
compra  0.812870  1.000000  0.471955  0.030844
ano     0.676109  0.471955  1.000000 -0.108081
mes     0.025015  0.030844 -0.108081  1.000000

## Gerar dataframe consolidado

In [30]:
# fazer marcaÃ§Ã£o de que certos valores foram imputados
df = df2.copy()
df['imputado'] = 0
df = pd.concat([df, df3])
df['imputado'] = df['imputado'].fillna(1)
df['imputado'] = df['imputado'].astype('uint8')
df

,regiao,uf,municipio,bairro,produto,venda,compra,ano,mes,bandeira,revenda,imputado
3,S,PR,PATO BRANCO,CENTRO,GASOLINA,3.680,3.039600,2017,7,RODOIL,SANTOS & MERLO LTDA.,0
9,N,AC,CRUZEIRO DO SUL,JOÃƒÂƒO ALVES,GASOLINA,4.700,3.575700,2017,7,BRANCA,CARDINAL E OLIVEIRA LTDA,0
13,N,AC,RIO BRANCO,ESTACAO EXPERIMENTAL,GASOLINA,3.830,3.282900,2017,7,PETROBRAS DISTRIBUIDORA S.A.,AUTO POSTO ISAURAO LTDA,0
14,N,AC,RIO BRANCO,ESTACAO EXPERIMENTAL,ETANOL,3.600,3.005600,2017,7,PETROBRAS DISTRIBUIDORA S.A.,AUTO POSTO ISAURAO LTDA,0
15,N,AC,RIO BRANCO,AVIARIO,GASOLINA,3.850,3.439900,2017,7,PETROBRAS DISTRIBUIDORA S.A.,COMDEPE COMERCIO DE DERIVADOS DE PETROLEO LTDA,0
...,...,...,...,...,...,...,...,...,...,...,...,...
2624160,SE,MG,MANHUACU,REALEZA,GASOLINA,4.790,4.298059,2018,6,RAIZEN,AUTO POSTO NAZARAO REALEZA LTDA,1
2624161,SE,MG,MANHUACU,REALEZA,ETANOL,2.990,2.608998,2018,6,RAIZEN,AUTO POSTO NAZARAO REALEZA LTDA,1
2624165,NE,PI,PARNAIBA,SAO BENEDITO,GASOLINA,4.850,4.245462,2018,6,PETROBRAS DISTRIBUIDORA S.A.,V. MACHADO & CIA LTDA,1
2624166,NE,BA,BARREIRAS,CENTRO,GASOLINA,4.599,4.037193,2018,6,PETROBRAS DISTRIBUIDORA S.A.,POSTO MACAUBENSE LTDA,1
2624167,NE,BA,BARREIRAS,CENTRO,ETANOL,3.049,2.558411,2018,6,PETROBRAS DISTRIBUIDORA S.A.,POSTO MACAUBENSE LTDA,1

In [31]:
#df = pd.concat([df2, df3])
#df

In [32]:
# arredondar valores para 4 casas decimais
for col in ['venda', 'compra']:
    df[col] = df[col].round(3)
df

,regiao,uf,municipio,bairro,produto,venda,compra,ano,mes,bandeira,revenda,imputado
3,S,PR,PATO BRANCO,CENTRO,GASOLINA,3.680,3.040,2017,7,RODOIL,SANTOS & MERLO LTDA.,0
9,N,AC,CRUZEIRO DO SUL,JOÃƒÂƒO ALVES,GASOLINA,4.700,3.576,2017,7,BRANCA,CARDINAL E OLIVEIRA LTDA,0
13,N,AC,RIO BRANCO,ESTACAO EXPERIMENTAL,GASOLINA,3.830,3.283,2017,7,PETROBRAS DISTRIBUIDORA S.A.,AUTO POSTO ISAURAO LTDA,0
14,N,AC,RIO BRANCO,ESTACAO EXPERIMENTAL,ETANOL,3.600,3.006,2017,7,PETROBRAS DISTRIBUIDORA S.A.,AUTO POSTO ISAURAO LTDA,0
15,N,AC,RIO BRANCO,AVIARIO,GASOLINA,3.850,3.440,2017,7,PETROBRAS DISTRIBUIDORA S.A.,COMDEPE COMERCIO DE DERIVADOS DE PETROLEO LTDA,0
...,...,...,...,...,...,...,...,...,...,...,...,...
2624160,SE,MG,MANHUACU,REALEZA,GASOLINA,4.790,4.298,2018,6,RAIZEN,AUTO POSTO NAZARAO REALEZA LTDA,1
2624161,SE,MG,MANHUACU,REALEZA,ETANOL,2.990,2.609,2018,6,RAIZEN,AUTO POSTO NAZARAO REALEZA LTDA,1
2624165,NE,PI,PARNAIBA,SAO BENEDITO,GASOLINA,4.850,4.245,2018,6,PETROBRAS DISTRIBUIDORA S.A.,V. MACHADO & CIA LTDA,1
2624166,NE,BA,BARREIRAS,CENTRO,GASOLINA,4.599,4.037,2018,6,PETROBRAS DISTRIBUIDORA S.A.,POSTO MACAUBENSE LTDA,1
2624167,NE,BA,BARREIRAS,CENTRO,ETANOL,3.049,2.558,2018,6,PETROBRAS DISTRIBUIDORA S.A.,POSTO MACAUBENSE LTDA,1

In [33]:
# gerar arquivo CSV com valores imputados
arquivo_saida = "ge-cv-2017-2022.csv.bz2"
df.to_csv(arquivo_saida, index=False, encoding='utf-8')