In [1]:
import pandas as pd

In [2]:
def normalizar_bandeira(titulo):
    if titulo in ['BRANCA', 'IPIRANGA', 'RAIZEN']:
        return titulo
    elif titulo == 'PETROBRAS DISTRIBUIDORA S.A.':
        return 'PETROBRAS'
    else:
        return 'OUTRAS'

In [8]:
# ler os dados do arquivo CSV
df = pd.read_csv("ge-cv-2015-2020.csv.bz2",
                 dtype={'regiao': 'category', 'uf': 'category', 
                        'municipio': 'category', 'bairro': 'category',
                        'produto': 'category', 'imputado': 'category',
                        'venda': 'float32', 'compra': 'float32',
                        'ano': 'uint16', 'mes': 'uint8'})

# limitar a quantidade de linhas
#if qtd_linhas:
#    df = df.sample(n=qtd_linhas, random_state=42)

# criar coluna ano/mês da coleta
#df['ams'] = df['ano'].astype('int') * 100 + df['mes'].astype('int')

# criar coluna data da coleta
#df['data'] = pd.to_datetime(df['ams'], format='%Y%m')

# criar colunas lucro e %lucro
df['margem'] = round(df['venda'] - df['compra'], 3)
df['pmargem'] = round((df['venda'] / df['compra'] - 1) * 100, 2)

# normalizar bandeira do posto
df['bandeira'] = df['bandeira'].apply(normalizar_bandeira)

In [9]:
df

,regiao,uf,municipio,bairro,produto,venda,compra,ano,mes,bandeira,revenda,imputado,margem,pmargem
0,S,PR,PATO BRANCO,CENTRO,GASOLINA,3.680,3.040,2017,7,OUTRAS,SANTOS & MERLO LTDA.,0,0.640,21.049999
1,N,AC,CRUZEIRO DO SUL,JOÃO ALVES,GASOLINA,4.700,3.576,2017,7,BRANCA,CARDINAL E OLIVEIRA LTDA,0,1.124,31.430000
2,N,AC,RIO BRANCO,ESTACAO EXPERIMENTAL,GASOLINA,3.830,3.283,2017,7,PETROBRAS,AUTO POSTO ISAURAO LTDA,0,0.547,16.660000
3,N,AC,RIO BRANCO,ESTACAO EXPERIMENTAL,ETANOL,3.600,3.006,2017,7,PETROBRAS,AUTO POSTO ISAURAO LTDA,0,0.594,19.760000
4,N,AC,RIO BRANCO,AVIARIO,GASOLINA,3.850,3.440,2017,7,PETROBRAS,COMDEPE COMERCIO DE DERIVADOS DE PETROLEO LTDA,0,0.410,11.920000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3212935,SE,MG,MANHUACU,REALEZA,GASOLINA,4.790,4.258,2018,6,RAIZEN,AUTO POSTO NAZARAO REALEZA LTDA,1,0.532,12.490000
3212936,SE,MG,MANHUACU,REALEZA,ETANOL,2.990,2.562,2018,6,RAIZEN,AUTO POSTO NAZARAO REALEZA LTDA,1,0.428,16.709999
3212937,NE,PI,PARNAIBA,SAO BENEDITO,GASOLINA,4.850,4.097,2018,6,PETROBRAS,V. MACHADO & CIA LTDA,1,0.753,18.379999
3212938,NE,BA,BARREIRAS,CENTRO,GASOLINA,4.599,4.015,2018,6,PETROBRAS,POSTO MACAUBENSE LTDA,1,0.584,14.550000
3212939,NE,BA,BARREIRAS,CENTRO,ETANOL,3.049,2.530,2018,6,PETROBRAS,POSTO MACAUBENSE LTDA,1,0.519,20.510000

In [19]:
df.drop(['mes'], axis=1).\
groupby([
    pd.Grouper(key='regiao'),
    pd.Grouper(key='uf'),
    pd.Grouper(key='produto'),
    pd.Grouper(key='bandeira'),
    pd.Grouper(key='ano'),
    #pd.Grouper(key='mes'),
]).mean().reset_index()

,regiao,uf,produto,bandeira,ano,venda,compra,margem,pmargem
0,S,PR,GASOLINA,BRANCA,2015,3.288905,2.875298,0.413607,14.406856
1,S,PR,GASOLINA,BRANCA,2016,3.667348,3.214187,0.453160,14.107924
2,S,PR,GASOLINA,BRANCA,2017,3.699806,3.240989,0.458818,14.231326
3,S,PR,GASOLINA,BRANCA,2018,4.297497,3.874757,0.422740,10.904242
4,S,PR,GASOLINA,BRANCA,2019,4.215832,3.836417,0.379415,9.886086
...,...,...,...,...,...,...,...,...,...
8095,SE,SP,ETANOL,RAIZEN,2016,2.519115,2.175479,0.343636,15.980131
8096,SE,SP,ETANOL,RAIZEN,2017,2.533115,2.173124,0.359991,16.669510
8097,SE,SP,ETANOL,RAIZEN,2018,2.754403,2.394794,0.359609,15.130219
8098,SE,SP,ETANOL,RAIZEN,2019,2.749117,2.422364,0.326753,13.503160
8099,SE,SP,ETANOL,RAIZEN,2020,2.771987,2.393815,0.378172,16.381382

In [ ]:
#source = base.groupby([pd.Grouper(key="data", freq="6M"), "bandeira"]).mean().reset_index()